#!/usr/bin/env python3
"""
gen_torizon.py — emit the synthetic Torizon-shaped metadata header from the
JSON fixtures under test/fixtures/torizon/.

The fixtures are SYNTHETIC (throwaway RSA-2048 keys, RSASSA-PSS-SHA256, no real
account data) produced by make_synthetic_torizon.py. This step just serializes
their raw bytes into C string literals so the host tests can run the on-device
verification core against real-shaped Torizon Cloud metadata (canonical JSON +
RSA-PSS signatures + the Image-repo meta-hash chain over the raw served bytes).

Pure serialization — no crypto — so it runs at test-build time.
"""
import os
import sys
import json

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "torizon")

# macro name -> source filename
FILES = {
    "TZ_ANCHOR_DIRECTOR_ROOT": "anchor_director_root.json",
    "TZ_ANCHOR_IMAGE_ROOT":    "anchor_image_root.json",
    "TZ_DIR_ROOT":             "director_root.json",
    "TZ_DIR_TIMESTAMP":        "director_timestamp.json",
    "TZ_DIR_SNAPSHOT":         "director_snapshot.json",
    "TZ_DIR_TARGETS":          "director_targets.json",
    "TZ_IMG_ROOT":             "repo_root.json",
    "TZ_IMG_TIMESTAMP":        "repo_timestamp.json",
    "TZ_IMG_SNAPSHOT":         "repo_snapshot.json",
    "TZ_IMG_TARGETS":          "repo_targets.json",
}


def c_escape(raw: bytes) -> str:
    out = []
    for b in raw:
        if b == 0x5C:      # backslash
            out.append("\\\\")
        elif b == 0x22:    # double quote
            out.append("\\\"")
        elif b == 0x0A:    # newline
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif b == 0x09:
            out.append("\\t")
        elif 0x20 <= b < 0x7F:
            out.append(chr(b))
        else:
            out.append("\\x%02x" % b)
    return "".join(out)


def the_target():
    """Extract the single synthetic target the Image repo signs (filepath, sha256,
    length) so the tests and fixtures share one source of truth."""
    with open(os.path.join(SRC, "repo_targets.json"), "rb") as f:
        env = json.load(f)
    targets = env["signed"]["targets"]
    fp = next(iter(targets))
    t = targets[fp]
    return fp, t["hashes"]["sha256"], int(t["length"])


def main():
    if len(sys.argv) != 2:
        print("usage: gen_torizon.py <out.h>", file=sys.stderr)
        return 2
    out_path = sys.argv[1]
    fp, sha, length = the_target()
    lines = [
        "/* GENERATED by test/fixtures/gen_torizon.py from the SYNTHETIC Torizon-",
        " * shaped fixtures under test/fixtures/torizon/ (throwaway RSA keys,",
        " * RSASSA-PSS-SHA256, no real account data). Do not edit by hand. */",
        "#pragma once",
        "",
        '#define TZ_TARGET_FILEPATH "%s"' % fp,
        '#define TZ_TARGET_SHA256   "%s"' % sha,
        "#define TZ_TARGET_LENGTH   %dL" % length,
        "",
    ]
    for macro, fname in FILES.items():
        with open(os.path.join(SRC, fname), "rb") as f:
            raw = f.read()
        lines.append("/* %s (%d bytes) */" % (fname, len(raw)))
        lines.append('#define %s "%s"' % (macro, c_escape(raw)))
        lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d fixtures)" % (out_path, len(FILES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
