#!/usr/bin/env bash
#
# sync-build.sh — author locally, build in Docker on a remote build host.
#
# The local checkout is the source of truth. This script:
#   1. Generates main/wifi_credentials.h from secrets/wifi.env (KEY=VALUE) when
#      that file is present (gitignored; never committed).
#   2. rsyncs the tree to the build host (excluding build dirs, .git, and
#      managed_components).
#   3. Runs idf.py inside the espressif/idf:release-v5.4 container on the build
#      host, once per target (esp32, esp32s3), into per-target build dirs.
#
# The build host is any machine with Docker (the user must be able to run docker
# without sudo) reachable over SSH. Configure it with environment variables (all
# have defaults):
#   AKTUALINO_BUILD_HOST   build host (default: localhost)
#   AKTUALINO_BUILD_USER   SSH user (default: none -> ssh uses its own default)
#   AKTUALINO_SSH_KEY      SSH private key (default: none -> ssh default keys)
#   AKTUALINO_REMOTE_DIR   project dir on the build host (default: aktualino)
#   AKTUALINO_IDF_IMAGE    ESP-IDF Docker image (default: espressif/idf:release-v5.4)
#   AKTUALINO_SERIAL_PORT  serial device for flash/monitor (default: /dev/ttyUSB0)
#
# Usage:
#   tools/sync-build.sh build            # both targets (default)
#   tools/sync-build.sh build esp32      # one target
#   tools/sync-build.sh clean [target]   # fullclean
#   tools/sync-build.sh monitor [target] # flash + serial monitor (needs the board)
#   tools/sync-build.sh gen-creds        # only regenerate generated headers
#
# Everything runs over SSH; NO sudo, Docker only.
set -euo pipefail

# --- config ----------------------------------------------------------------
BUILD_HOST="${AKTUALINO_BUILD_HOST:-localhost}"
BUILD_USER="${AKTUALINO_BUILD_USER:-}"
SSH_KEY="${AKTUALINO_SSH_KEY:-}"
REMOTE_DIR="${AKTUALINO_REMOTE_DIR:-aktualino}"
IDF_IMAGE="${AKTUALINO_IDF_IMAGE:-espressif/idf:release-v5.4}"
SERIAL_DEV="${AKTUALINO_SERIAL_PORT:-/dev/ttyUSB0}"
DEFAULT_TARGETS=(esp32 esp32s3)

REMOTE_HOST="${BUILD_USER:+$BUILD_USER@}$BUILD_HOST"

# Repo root = parent of this script's dir.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

SSH=(ssh -o StrictHostKeyChecking=accept-new)
[[ -n "$SSH_KEY" ]] && SSH+=(-i "$SSH_KEY")
SSH_BASE="${SSH[*]}"
SSH+=("$REMOTE_HOST")

log() { printf '\033[1;36m[sync-build]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[sync-build] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. generate main/wifi_credentials.h from secrets/wifi.env -------------
gen_creds() {
    local env_file="secrets/wifi.env"
    local out="main/wifi_credentials.h"
    if [[ ! -f "$env_file" ]]; then
        log "no $env_file — skipping wifi_credentials.h (Kconfig fallback used)"
        return 0
    fi
    local ssid="" pass=""
    # Read KEY=VALUE; ignore comments/blank lines. Strip surrounding quotes.
    while IFS='=' read -r key val; do
        key="${key#"${key%%[![:space:]]*}"}"   # ltrim
        [[ -z "$key" || "$key" == \#* ]] && continue
        val="${val%$'\r'}"                       # strip CR
        val="${val#\"}"; val="${val%\"}"         # strip quotes
        case "$key" in
            WIFI_SSID) ssid="$val" ;;
            WIFI_PASS|WIFI_PASSWORD) pass="$val" ;;
        esac
    done < "$env_file"
    [[ -n "$ssid" ]] || die "$env_file has no WIFI_SSID"

    # Escape backslashes and double-quotes for a C string literal.
    esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
    {
        echo "/* GENERATED by tools/sync-build.sh from secrets/wifi.env — DO NOT COMMIT. */"
        echo "#pragma once"
        echo "#define AKTUALINO_WIFI_SSID \"$(esc "$ssid")\""
        echo "#define AKTUALINO_WIFI_PASS \"$(esc "$pass")\""
        # Marker: real baked creds (vs the Kconfig placeholder). main uses it to
        # decide whether Wi-Fi is "known" (else it opens the SoftAP portal).
        echo "#define AKTUALINO_HAVE_BAKED_WIFI 1"
    } > "$out"
    log "wrote $out (SSID \"$ssid\")"
}

# --- 1c. generate main/provision_client.h (Torizon A2 self-provision) --------
# DEV-ONLY: bakes the Torizon provisioning client (provision.json) + the two
# public Torizon RSA roots so one image self-provisions to Torizon Cloud with no
# per-device injection (docs/provisioning.md Path A2). The header carries the
# account client_secret -> .gitignored, NEVER committed, needs flash encryption
# in production. Absent inputs are a soft skip (A2 disabled; injected/Path-B
# still work).
gen_provision_client() {
    local prov="secrets/torizon/extracted/provision.json"
    local dir_root="secrets/torizon/extracted/director.root.json"
    local img_root="secrets/torizon/extracted/root.json"
    local out="main/provision_client.h"
    if [[ ! -f "$prov" || ! -f "$dir_root" || ! -f "$img_root" ]]; then
        log "no Torizon provision.json/roots — skipping provision_client.h (A2 disabled)"
        rm -f "$out"
        return 0
    fi
    python3 - "$prov" "$dir_root" "$img_root" "$out" <<'PY'
import json, sys
prov = json.load(open(sys.argv[1]))
# json.dumps of ASCII file content is also a valid C string literal (\" \\ \n ...).
def cstr(path): return json.dumps(open(path).read())
with open(sys.argv[4], "w") as f:
    f.write("/* GENERATED by tools/sync-build.sh from secrets/torizon/ — DO NOT COMMIT (client_secret). */\n")
    f.write("#pragma once\n")
    f.write("#define AKTUALINO_TORIZON_PROVISION 1\n")
    f.write("#define AKTUALINO_TORIZON_CLIENT_ID %s\n" % json.dumps(prov["client_id"]))
    f.write("#define AKTUALINO_TORIZON_CLIENT_SECRET %s\n" % json.dumps(prov["secret"]))
    f.write("#define AKTUALINO_TORIZON_TOKEN_ENDPOINT %s\n" % json.dumps(prov["token_endpoint"]))
    f.write("#define AKTUALINO_TORIZON_DIRECTOR_ROOT %s\n" % cstr(sys.argv[2]))
    f.write("#define AKTUALINO_TORIZON_IMAGE_ROOT %s\n" % cstr(sys.argv[3]))
PY
    log "wrote $out (Torizon A2 client baked — DO NOT COMMIT)"
}

# --- 2. rsync local checkout -> build host ---------------------------------
sync() {
    log "rsync -> $REMOTE_HOST:~/$REMOTE_DIR/"
    rsync -a --delete \
        --exclude 'build' --exclude 'build-*' --exclude '.git' \
        --exclude 'managed_components' --exclude 'sdkconfig' \
        -e "$SSH_BASE" \
        "$REPO_ROOT/" "$REMOTE_HOST:$REMOTE_DIR/"
}

# Run idf.py inside the container against ~/aktualino (mounted at /project).
# $1 = extra docker flags (e.g. --device); rest = idf.py args.
idf_run() {
    local docker_flags="$1"; shift
    # Forward the build-time feature flags (read by main/CMakeLists.txt inside the
    # container) only when set in this shell, so a normal build is unaffected.
    local envs=""
    [[ -n "${AKT_ROLLBACK_TEST:-}" ]] && envs="$envs -e AKT_ROLLBACK_TEST=$AKT_ROLLBACK_TEST"
    [[ -n "${AKT_PORTAL_TEST:-}" ]]   && envs="$envs -e AKT_PORTAL_TEST=$AKT_PORTAL_TEST"
    # shellcheck disable=SC2086
    "${SSH[@]}" "docker run --rm $docker_flags $envs \
        -v \$HOME/$REMOTE_DIR:/project -w /project \
        $IDF_IMAGE idf.py $*"
}

build_target() {
    local t="$1"
    log "build target=$t (build-$t/)"
    idf_run "" "-B build-$t set-target $t build"
    log "target=$t OK"
}

clean_target() {
    local t="$1"
    log "fullclean target=$t"
    idf_run "" "-B build-$t fullclean" || true
}

monitor_target() {
    local t="$1"
    log "flash + monitor target=$t on $SERIAL_DEV (needs the board attached)"
    # Container runs as root so it can open the serial tty.
    idf_run "--device=$SERIAL_DEV" \
        "-B build-$t -p $SERIAL_DEV flash monitor"
}

# --- dispatch ---------------------------------------------------------------
cmd="${1:-build}"; shift || true
case "$cmd" in
    gen-creds)
        gen_creds
        gen_provision_client
        ;;
    build)
        gen_creds
        gen_provision_client
        sync
        if [[ $# -gt 0 ]]; then targets=("$@"); else targets=("${DEFAULT_TARGETS[@]}"); fi
        for t in "${targets[@]}"; do build_target "$t"; done
        log "all builds done: ${targets[*]}"
        ;;
    clean)
        sync
        if [[ $# -gt 0 ]]; then targets=("$@"); else targets=("${DEFAULT_TARGETS[@]}"); fi
        for t in "${targets[@]}"; do clean_target "$t"; done
        ;;
    monitor)
        gen_creds
        gen_provision_client
        sync
        monitor_target "${1:-esp32}"
        ;;
    *)
        die "unknown command: $cmd (want build|clean|monitor|gen-creds)"
        ;;
esac
